# Generated by Django 3.1.3 on 2020-11-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=120, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
